-- PostgreSQL schema. Kept in step with migrations/sqlite/*.sql; timestamps are
-- stored as text ('YYYY-MM-DD HH24:MI:SS', UTC) to match the Go layer.

-- Accounts --------------------------------------------------------------

CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         TEXT NOT NULL UNIQUE,
    display_name  TEXT NOT NULL DEFAULT '',
    password_hash TEXT NOT NULL,
    created_at    TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE sessions (
    token      TEXT PRIMARY KEY,
    user_id    BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
    expires_at TEXT NOT NULL
);
CREATE INDEX sessions_user_idx ON sessions(user_id);

-- Content --------------------------------------------------------------

CREATE TABLE projects (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    slug       TEXT NOT NULL,
    name       TEXT NOT NULL,
    sort       INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
    UNIQUE (user_id, slug)
);

CREATE TABLE entries (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    slug       TEXT NOT NULL,
    title      TEXT NOT NULL DEFAULT '',
    body       TEXT NOT NULL DEFAULT '',
    status     TEXT NOT NULL DEFAULT '',
    priority   INTEGER NOT NULL DEFAULT 0,
    due        TEXT,
    project_id BIGINT REFERENCES projects(id) ON DELETE SET NULL,
    parent_id  BIGINT REFERENCES entries(id) ON DELETE CASCADE,
    board_sort DOUBLE PRECISION NOT NULL DEFAULT 0,
    pinned     INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL DEFAULT '',
    updated_at TEXT NOT NULL DEFAULT '',
    done_at    TEXT,
    search     tsvector,
    UNIQUE (user_id, slug)
);
CREATE INDEX entries_board_idx   ON entries(user_id, status, board_sort);
CREATE INDEX entries_due_idx     ON entries(user_id, due);
CREATE INDEX entries_parent_idx  ON entries(parent_id);
CREATE INDEX entries_project_idx ON entries(project_id);
CREATE INDEX entries_search_idx  ON entries USING GIN(search);

CREATE TABLE tags (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    name    TEXT NOT NULL,
    UNIQUE (user_id, name)
);

CREATE TABLE entry_tags (
    entry_id BIGINT NOT NULL REFERENCES entries(id) ON DELETE CASCADE,
    tag_id   BIGINT NOT NULL REFERENCES tags(id) ON DELETE CASCADE,
    PRIMARY KEY (entry_id, tag_id)
);
CREATE INDEX entry_tags_tag_idx ON entry_tags(tag_id);

CREATE TABLE links (
    src_id BIGINT NOT NULL REFERENCES entries(id) ON DELETE CASCADE,
    dst_id BIGINT NOT NULL REFERENCES entries(id) ON DELETE CASCADE,
    PRIMARY KEY (src_id, dst_id)
);
CREATE INDEX links_dst_idx ON links(dst_id);
