// Command pgimport copies a Cairn SQLite database into a Postgres database.
//
//	go run ./cmd/pgimport -from data/cairn.db -to "$DATABASE_URL"
//
// The destination schema is created if missing (the same migrations the app
// runs). The tables it touches are emptied first, so the import is repeatable.
// Sessions are skipped — users sign in again.
package main

import (
	"context"
	"database/sql"
	"flag"
	"fmt"
	"log"
	"os"
	"strings"

	_ "github.com/jackc/pgx/v5/stdlib"
	_ "modernc.org/sqlite"

	"taskmanager/internal/store"
)

// FK-safe order.
var tables = []string{
	"users", "projects", "calendars", "tags",
	"entries", "entry_tags", "links", "events", "settings",
}

func main() {
	from := flag.String("from", "", "path to the SQLite cairn.db")
	to := flag.String("to", os.Getenv("DATABASE_URL"), "destination postgres:// URL")
	flag.Parse()

	if *from == "" || *to == "" {
		log.Fatal("usage: pgimport -from data/cairn.db -to postgres://…")
	}
	if !store.IsPostgresDSN(*to) {
		log.Fatalf("-to must be a postgres:// URL, got %q", *to)
	}

	src, err := sql.Open("sqlite", "file:"+*from+"?_pragma=foreign_keys(OFF)")
	if err != nil {
		log.Fatalf("open sqlite: %v", err)
	}
	defer src.Close()
	if err := src.Ping(); err != nil {
		log.Fatalf("sqlite unreadable: %v", err)
	}

	// store.Open runs the Postgres migrations.
	dstStore, err := store.Open(*to)
	if err != nil {
		log.Fatalf("open/migrate postgres: %v", err)
	}
	defer dstStore.Close()
	dst := dstStore.SQL()

	ctx := context.Background()
	tx, err := dst.BeginTx(ctx, nil)
	if err != nil {
		log.Fatal(err)
	}
	defer tx.Rollback()

	if _, err := tx.ExecContext(ctx,
		`TRUNCATE `+strings.Join(tables, ", ")+` RESTART IDENTITY CASCADE`); err != nil {
		log.Fatalf("truncate: %v", err)
	}

	total := 0
	for _, table := range tables {
		n, err := copyTable(ctx, src, tx, table)
		if err != nil {
			log.Fatalf("%s: %v", table, err)
		}
		log.Printf("%-12s %5d rows", table, n)
		total += n
	}

	if err := fixParents(ctx, src, tx); err != nil {
		log.Fatalf("relink subtasks: %v", err)
	}
	if _, err := tx.ExecContext(ctx,
		`UPDATE entries SET search = to_tsvector('english', coalesce(title,'') || ' ' || coalesce(body,''))`); err != nil {
		log.Fatalf("rebuild search: %v", err)
	}
	if err := bumpSequences(ctx, tx); err != nil {
		log.Fatalf("bump sequences: %v", err)
	}

	if err := tx.Commit(); err != nil {
		log.Fatal(err)
	}
	log.Printf("done — %d rows imported into Postgres", total)
}

// copyTable streams every row of one table from SQLite into Postgres, keeping
// ids. For `entries`, parent_id is nulled here and restored by fixParents.
func copyTable(ctx context.Context, src *sql.DB, tx *sql.Tx, table string) (int, error) {
	rows, err := src.QueryContext(ctx, "SELECT * FROM "+table)
	if err != nil {
		return 0, err
	}
	defer rows.Close()

	cols, err := rows.Columns()
	if err != nil {
		return 0, err
	}
	parentIdx := indexOf(cols, "parent_id")

	ph := make([]string, len(cols))
	for i := range ph {
		ph[i] = fmt.Sprintf("$%d", i+1)
	}
	// The id columns are GENERATED BY DEFAULT AS IDENTITY, so explicit values
	// are accepted; bumpSequences fixes the sequence afterwards.
	insert := fmt.Sprintf("INSERT INTO %s (%s) VALUES (%s)",
		table, strings.Join(cols, ", "), strings.Join(ph, ", "))

	n := 0
	for rows.Next() {
		vals := make([]any, len(cols))
		ptrs := make([]any, len(cols))
		for i := range vals {
			ptrs[i] = &vals[i]
		}
		if err := rows.Scan(ptrs...); err != nil {
			return n, err
		}
		if table == "entries" && parentIdx >= 0 {
			vals[parentIdx] = nil
		}
		if _, err := tx.ExecContext(ctx, insert, vals...); err != nil {
			return n, err
		}
		n++
	}
	return n, rows.Err()
}

func fixParents(ctx context.Context, src *sql.DB, tx *sql.Tx) error {
	rows, err := src.QueryContext(ctx,
		`SELECT id, parent_id FROM entries WHERE parent_id IS NOT NULL`)
	if err != nil {
		return err
	}
	defer rows.Close()
	for rows.Next() {
		var id, parent int64
		if err := rows.Scan(&id, &parent); err != nil {
			return err
		}
		if _, err := tx.ExecContext(ctx,
			`UPDATE entries SET parent_id = $1 WHERE id = $2`, parent, id); err != nil {
			return err
		}
	}
	return rows.Err()
}

// bumpSequences moves each IDENTITY sequence past the largest imported id.
func bumpSequences(ctx context.Context, tx *sql.Tx) error {
	for _, table := range []string{"users", "projects", "calendars", "tags", "entries", "events"} {
		_, err := tx.ExecContext(ctx, fmt.Sprintf(
			`SELECT setval(pg_get_serial_sequence('%s','id'), GREATEST((SELECT COALESCE(MAX(id),1) FROM %s), 1))`,
			table, table))
		if err != nil {
			return err
		}
	}
	return nil
}

func indexOf(ss []string, want string) int {
	for i, s := range ss {
		if s == want {
			return i
		}
	}
	return -1
}
